version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '${POSTGRES_PORT_EXT:-5432}:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
